BookingTicket/ViewModels/MovieViewModels.cs
using BookingTicket.Entities.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BookingTicket.ViewModels
{
    public class MovieViewListingModel
    {
        public List<Movie> Movies { get; set; }
    }

    public class MovieViewModel
    {
        public Movie Movie { get; set; }
        public List<Projection> Projection { get; set; }
    }

    public class MovieTimeViewModel
    {
        public List<Projection> Projections { get; set; }
    }

}

BookingTicket/Controllers/MovieController.cs
using BookingTicket.Entities.Entities;
using BookingTicket.Service;
using BookingTicket.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookingTicket.Controllers
{
    public class MovieController : Controller
    {
        // GET: Movie
        public ActionResult Index()
        {
            var model = new MovieViewListingModel();
            model.Movies = MovieService.GetLastMovies(8);
            return View(model);
        }

        public ActionResult Details(string Id)
        {
            var model = new MovieViewModel();
            model.Movie = MovieService.GetMovieById(Id);
            model.Projection = ProjectionService.GetProjectionsByMovieId(Id);
            return View(model);
        }

        [HttpPost]
        public ActionResult GetTimeForMovie(string Id)
        {
           
           MovieTimeViewModel model = new MovieTimeViewModel();
           model.Projections = ProjectionService.GetProjectionsByMovieId(Id);  

           return PartialView(model);
        }

        #region Create
        public ActionResult AddMovie()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult AddMovie(Movie movie)
        {
            MovieService.AddMovie(movie);
            return RedirectToAction("Index", "Movie");
        }
        #endregion

        #region Update
        public ActionResult EditMovie(string Id)
        {
            var model = new MovieViewModel();
            model.Movie = MovieService.GetMovieById(Id);
            return PartialView(model);
        }

        [HttpPost]
        public ActionResult EditMovie(Movie movie)
        {
            if(movie != null)
            {
                MovieService.EditMovie(movie);
            }
            return RedirectToAction("Index", "Movie");
        }
        #endregion

        #region Delete
        public ActionResult DeleteMovie(string Id)
        {
            MovieService.DeleteMovie(Id);
            return RedirectToAction("Index", "Movie");
        }
        #endregion
    }
}

BookingTicket/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookingTicket.Controllers
{
    public class SharedController : Controller
    {
        public JsonResult UploadImage()
        {
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;

            try
            {
                var file = Request.Files[0];

                var fileName = Guid.NewGuid() + Path.GetExtension(file.FileName);

                var path = Path.Combine(Server.MapPath("~/content/images/"), fileName);

                file.SaveAs(path);

                result.Data = new { Success = true, ImageUrl = string.Format("/content/images/{0}", fileName) };

            }
            catch (Exception ex)
            {
                result.Data = new { Success = false, Message = ex.Message };
            }
            return result;
        }
    }
}

BookingTicket/Views/Movie/AddMovie.cshtml
<div class="container row">
    <h2 class="page-heading">Novi film</h2>
    <form id="addMovieForm" class="col-md-8">
        <div class="form-group" style="margin: 5px;">
            <label for="Title">Titl <span style="color:red;">*</span></label>
            <br />
            <input class="form-control" id="Title" name="Title" placeholder="Titl" required />
        </div>
        <div class="form-group" style="margin: 5px;">
            <label for="Starring">Glumci <span style="color:red;">*</span></label>
            <br />
            <input class="form-control" id="Starring" name="Starring" placeholder="U glavnoj ulozi" required />
        </div>


        <div class="form-group" style="margin: 5px;">
            <label for="Genre">Žanr <span style="color:red;">*</span></label>
            <br />
            <input class="form-control" id="Genre" name="Genre" placeholder="Žanr" required />
        </div>
        <div class="form-group" style="margin: 5px;">
            <label for="RunTime">Vreme trajanja <span style="color:red;">*</span></label>
            <br />
            <input type="number" class="form-control" id="RunTime" name="RunTime" placeholder="Vreme trajanja" required />
        </div>

        <div class="form-group" style="margin: 5px;">
            <label for="Description">Deskripcija</label>
            <br />
            <textarea rows="4" class="form-control" id="Description" name="Description" placeholder="Opis filma..."></textarea>
        </div>

        <div class="form-group " style="margin: 5px;">
            <label for="ReleaseDate">Datum izlaska</label>
            <br />
            <input class="form-control" id="ReleaseDate" name="ReleaseDate" placeholder="Datum izlaska"/>
        </div>
        <div class="form-group" style="margin: 5px;">
            <input type="hidden" name="ImageUrl" id="ImageUrl" />
            <label>Poster</label>
            <br />
            <input type="file" accept=".jpg, .png" class="form-control" id="imageUpload" name="Image" autocomplete="off" />
        </div>
        <div class="form-group" style="margin: 5px;">
            <a id="addNewMovieBtn" class="btn btn--default">Sačuvaj</a>
            <a id="cancleMovieBtn" class="btn btn--danger">Nazad</a>
        </div>
    </form>
    <div class="col-md-4">
        <img id="movieImage" style="height:350px; width:250px;" src="~/Content/images/banners/noImage.jpg" />
    </div>
</div>
<script>
    $('#addMovieForm').validate({
        rules: {
            Title: {
                required: true
            },
            Starring: {
                required: true
            },
            Genre: {
                required: true
            },
            RunTime: {
                required: true
            }
        },
        messages: {
            Title: {
                required: 'Ovo polje je obavezno!'
            },
            Starring: {
                required: 'Ovo polje je obavezno!'
            },
            Genre: {
                required: 'Ovo polje je obavezno!'
            },
            RunTime: {
                required: 'Ovo polje je obavezno!'
            }
        }
    });

    $("#addNewMovieBtn").click(function () {
        if ($("#addMovieForm").valid()) {
            $.ajax({
                type: 'POST',
                url: '@Url.Action("AddMovie", "Movie")',
                data: $("#addMovieForm").serialize()
            })
                .done(function (response) {
                    $("#movieActionContainer").html("");
                    swal("Gotovo", "Film je uspešno dodat.", "success").then((value) => {
                        window.location = '@Url.Action("Index","Movie")';
                    });
                })
                .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                    alert("FAIL");
                });
        }
        else {
            swal({
                title: "Upozorenje!",
                text: "Popunite sva polja koja su označena zvezdicom!",
                icon: "warning",
                dangerMode: true,
            });
        }
    });

    $("#cancleMovieBtn").click(function () {
        $("#movieActionContainer").html("");
        focusAction("movieMainContainer");
    });

    $("#imageUpload").change(function () {

        debugger;
    var element = this;
    var formData = new FormData();
    var totalFiles = element.files.length;

    for (var i = 0; i < totalFiles; i++) {
        var file = element.files[i];
        formData.append("Photo", file);
    }

    $.ajax({
        type: 'POST',
        url: '@Url.Action("UploadImage", "Shared")',
        dataType: 'json',
        data: formData,
        contentType: false,
        processData: false
    })
        .done(function (response) {
            console.log(response);
            if (response.Success) {
                $("#movieImage").attr("src", response.ImageUrl);
                $("#ImageUrl").val(response.ImageUrl);
            }
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("Fail")
        });
});
</script>

BookingTicket/Views/Movie/Details.cshtml
@model BookingTicket.ViewModels.MovieViewModel
@{
    ViewBag.Title = "Details";
}

<!-- Main content -->
<section class="container" style="margin-top: 40px;">
    <div class="col-sm-12">
        <div class="movie">
            <h2 class="page-heading">@Model.Movie.Title</h2>

            <div class="movie__info">
                <div class="col-sm-4  movie-mobile">
                    <div class="movie__images">
                       
                        <img alt='' src="@Model.Movie.ImageUrl">
                    </div>
                   
                </div>

                <div class="col-sm-8 ">
                    <p class="movie__time">@Model.Movie.RunTime min</p>
                    <p class="movie__option"><strong>Category: </strong><a href="#">@Model.Movie.Genre</a></p>
                    <p class="movie__option"><strong>Release date: </strong>@Model.Movie.ReleaseDate</p>
                    <p class="movie__option"><strong>Actors: </strong><a href="#">@Model.Movie.Starring</a><a href="#">...</a></p>
                    

          

                   
                </div>
            </div>

            <div class="clearfix"></div>

            <h2 class="page-heading">The plot</h2>

            <p class="movie__describe">@Model.Movie.Description</p>

            <h2 class="page-heading">photos &amp; videos</h2>

            <div class="movie__media">
                <div class="movie__media-switch">
                    <a href="#" class="watchlist list--photo" data-filter='media-photo'>234 photos</a>
                    <a href="#" class="watchlist list--video" data-filter='media-video'>10 videos</a>
                </div>

                <div class="swiper-container">
                    <div class="swiper-wrapper">
                        <!--First Slide-->
                        <div class="swiper-slide media-video">
                            <a href='https://www.youtube.com/watch?v=Y5AehBA3IsE' class="movie__media-item ">
                                <img alt='' src="http://placehold.it/400x240">
                            </a>
                        </div>

                        <!--Second Slide-->
                        <div class="swiper-slide media-video">
                            <a href='https://www.youtube.com/watch?v=Kb3ykVYvT4U' class="movie__media-item">
                                <img alt='' src="http://placehold.it/400x240">
                            </a>
                        </div>

                        <!--Third Slide-->
                        <div class="swiper-slide media-photo">
                            <a href='http://placehold.it/2100x1250' class="movie__media-item">
                                <img alt='' src="http://placehold.it/400x240">
                            </a>
                        </div>

                        <!--Four Slide-->
                        <div class="swiper-slide media-photo">
                            <a href='http://placehold.it/2100x1250' class="movie__media-item">
                                <img alt='' src="http://placehold.it/400x240">
                            </a>
                        </div>

                        <!--Slide-->
                        <div class="swiper-slide media-photo">
                            <a href='http://placehold.it/2100x1250' class="movie__media-item">
                                <img alt='' src="http://placehold.it/400x240">
                            </a>
                        </div>

                        <!--Slide-->
                        <div class="swiper-slide media-photo">
                            <a href='http://placehold.it/2100x1250' class="movie__media-item">
                                <img alt='' src="http://placehold.it/400x240">
                            </a>
                        </div>

                        <!--First Slide-->
                        <div class="swiper-slide media-video">
                            <a href='https://www.youtube.com/watch?v=Y5AehBA3IsE' class="movie__media-item ">
                                <img alt='' src="http://placehold.it/400x240">
                            </a>
                        </div>

                        <!--Second Slide-->
                        <div class="swiper-slide media-video">
                            <a href='https://www.youtube.com/watch?v=Kb3ykVYvT4U' class="movie__media-item">
                                <img alt='' src="http://placehold.it/400x240">
                            </a>
                        </div>

                        <!--Slide-->
                        <div class="swiper-slide media-photo">
                            <a href='http://placehold.it/2100x1250' class="movie__media-item">
                                <img alt='' src="http://placehold.it/400x240">
                            </a>
                        </div>

                        <!--Slide-->
                        <div class="swiper-slide media-photo">
                            <a href='http://placehold.it/2100x1250' class="movie__media-item">
                                <img alt='' src="http://placehold.it/400x240">
                            </a>
                        </div>

                    </div>
                </div>

            </div>

        <h2 class="page-heading">showtime &amp; tickets</h2>
        <div class="choose-container">
           

            <div class="clearfix"></div>

            <div class="time-select">
                <div class="time-select__group group--first">
                    <div class="col-sm-4">
                        <p class="time-select__place">Cineworld</p>
                    </div>
                    <ul class="col-sm-8 items-wrap">
                        @foreach (var time in Model.Projection)
                        {
                            <li class="time-select__item" data-time='@time.Time'>@time.Time</li>
                        }
                    </ul>
                </div>
            </div>


        </div>
    </div>

</section>

<div class="clearfix"></div>

<script type="text/javascript">
    $(document).ready(function () {
        init_MoviePage();
        init_MoviePageFull();
    });
</script>

BookingTicket/Views/Movie/EditMovie.cshtml
@model BookingTicket.ViewModels.MovieViewModel
@{ 
    var imageUrl = !string.IsNullOrEmpty(Model.Movie.ImageUrl) ? Model.Movie.ImageUrl : "~/Content/images/banners/noImage.jpg";
}
<div class="container row">
    <h2 class="page-heading">Izmeni film</h2>
    <form class="col-md-8" id="editMovieForm">
        <div class="form-group" style="margin: 5px;">
            <label for="Title">Titl <span style="color:red;">*</span></label>
            <br />
            <input class="form-control" id="Title" name="Title" placeholder="Titl" value="@Model.Movie.Title" required />
        </div>
        <div class="form-group" style="margin: 5px;">
            <label for="Starring">Glumci <span style="color:red;">*</span></label>
            <br />
            <input class="form-control" id="Starring" name="Starring" placeholder="U glavnoj ulozi" value="@Model.Movie.Starring" required />
        </div>

        <div class="form-group" style="margin: 5px;">
            <label for="Genre">Žanr <span style="color:red;">*</span></label>
            <br />
            <input class="form-control" id="Genre" name="Genre" placeholder="Žanr" value="@Model.Movie.Genre" required />
        </div>
        <div class="form-group" style="margin: 5px;">
            <label for="RunTime">Vreme trajanja <span style="color:red;">*</span></label>
            <br />
            <input type="number" class="form-control" id="RunTime" name="RunTime" placeholder="Vreme trajanja" value="@Model.Movie.RunTime" required />
        </div>

        <div class="form-group" style="margin: 5px;">
            <label for="Description">Deskripcija</label>
            <br />
            <input class="form-control" id="Description" name="Description" placeholder="Opis filma..." value="@Model.Movie.Description" />
        </div>

        <div class="form-group " style="margin: 5px;">
            <label for="ReleaseDate">Datum izlaska</label>
            <br />
            <input class="form-control" id="ReleaseDate" name="ReleaseDate" placeholder="Datum izlaska" value="@Model.Movie.ReleaseDate" />
        </div>
        <div class="form-group" style="margin: 5px;">
            <input type="hidden" id="ImageUrl" name="ImageUrl" value="@Model.Movie.ImageUrl" />
            <input type="file" accept=".jpg, .png" class="form-control" id="imageUpload" name="Image" autocomplete="off" />
        </div>
        <input type="hidden" value="@Model.Movie.MovieId" id="MovieId" name="MovieId" />
        <div class="form-group" style="margin: 5px;">
            <a id="editMovieBtn" class="btn btn--default">Sačuvaj izmene</a>
            <a id="cancleEditMovieBtn" class="btn btn--danger">Nazad</a>
        </div>
    </form>
    <div class="col-md-4">
        <img id="movieImage" style="height:350px; width:250px;" src="@imageUrl" />
    </div>
</div>

<script>
    $('#editMovieForm').validate({
        rules: {
            Title: {
                required: true
            },
            Starring: {
                required: true
            },
            Genre: {
                required: true
            },
            RunTime: {
                required: true
            }
        },
        messages: {
            Title: {
                required: 'Ovo polje je obavezno!'
            },
            Starring: {
                required: 'Ovo polje je obavezno!'
            },
            Genre: {
                required: 'Ovo polje je obavezno!'
            },
            RunTime: {
                required: 'Ovo polje je obavezno!'
            }
        }
    });

    $("#editMovieBtn").click(function () {
        if ($("#editMovieForm").valid()) {
            $.ajax({
                type: 'POST',
                url: '@Url.Action("EditMovie", "Movie")',
                data: $("#editMovieForm").serialize()
            })
                .done(function (response) {
                    $("#movieActionContainer").html("");
                    swal("Gotovo", "Film je uspešno izmenjen.", "success").then((value) => {
                        window.location = '@Url.Action("Index","Movie")';
                    });
                })
                .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                    alert("FAIL");
                });
        } else {
            swal({
                title: "Upozorenje!",
                text: "Popunite sva polja koja su označena zvezdicom!",
                icon: "warning",
                dangerMode: true,
            });
        }
    });

    $("#cancleEditMovieBtn").click(function () {
        $("#movieActionContainer").html("");
        focusAction("movieMainContainer");
    });

    $("#imageUpload").change(function () {

        
    var element = this;
    var formData = new FormData();
    var totalFiles = element.files.length;

    for (var i = 0; i < totalFiles; i++) {
        var file = element.files[i];
        formData.append("Photo", file);
    }

    $.ajax({
        type: 'POST',
        url: '@Url.Action("UploadImage", "Shared")',
        dataType: 'json',
        data: formData,
        contentType: false,
        processData: false
    })
        .done(function (response) {
            console.log(response);
            if (response.Success) {
                $("#movieImage").attr("src", response.ImageUrl);
                $("#ImageUrl").val(response.ImageUrl);
            }
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("Fail")
        });
});
</script>

BookingTicket/Views/Movie/GetTimeForMovie.cshtml
@model  BookingTicket.ViewModels.MovieTimeViewModel

@if (Model.Projections != null && Model.Projections.Count > 0)
{
    <h2 class="page-heading">Izaberi vreme</h2>
    <div class="time-select time-select--wide">
        <div class="time-select__group group--first">
            <div class="col-sm-3">
                <p class="time-select__place">Cineplek</p>
            </div>
            <ul class="col-sm-6 items-wrap">
                @foreach (var time in Model.Projections)
                {
                    <li class="time-select__item" data-time='@time.Time'>@time.Time</li>
                }
            </ul>
        </div>
    </div>
    <div class="choose-indector choose-indector--time">
        <strong>Izabrano: </strong><span class="choosen-area"></span>
    </div>

    <script>
        var movie = $('.choosen-movie'),
            city = $('.choosen-city'),
            date = $('.choosen-date'),
            cinema = $('.choosen-cinema'),
            time = $('.choosen-time');

       
        $('.time-select__item').click(function () {

            //visual iteractive for choose
            $('.time-select__item').removeClass('active');
            $(this).addClass('active');

            //data element init
            var chooseTime = $(this).attr('data-time');
            $('.choose-indector--time').find('.choosen-area').text(chooseTime);

            //data element init
            var chooseCinema = $(this).parent().parent().find('.time-select__place').text();

            //data element set
            time.val(chooseTime);
            cinema.val(chooseCinema);
        });

        $('.choose-indector--time').click(function (e) {

            e.preventDefault();
            $(this).toggleClass('hide-content');
            $('.time-select').slideToggle(400);
        });
    </script>
}
else
{
    <div class="alert alert-warning">
        <h2>Još uvek nema ni jedna projekcija za ovaj film!</h2>
    </div>
}

BookingTicket/Views/Movie/Index.cshtml
@model BookingTicket.ViewModels.MovieViewListingModel
@{
    ViewBag.Title = "Index";
}

<!-- Main content -->
<section class="container" style="margin-top: 50px;" id="movieMainContainer">
    <div class="col-sm-12">
        <h2 class="page-heading">Filmovi</h2>

        <div style="padding:20px;">
            <div style="float:right;">
                <a id="newMovieBtn" class="btn btn-md btn--warning btn--book btn-control--home">Dodaj film</a>
            </div>
        </div>
        <hr />
        @foreach (var movie in Model.Movies)
        {
            <!-- Movie preview item -->
            <div class="movie movie--preview movie--full release">
                <div class="col-sm-3 col-md-2 col-lg-2">
                    <div class="movie__images">
                        <img alt='image' src="@movie.ImageUrl">
                    </div>
                </div>

                <div class="col-sm-9 col-md-10 col-lg-10 movie__about">
                    <a href='movie-page-full.html' class="movie__title link--huge">@movie.Title</a>

                    <p class="movie__time">@movie.RunTime min</p>


                    <p class="movie__option"><strong>Category: </strong><a href="#">@movie.Genre</a></p>
                    <p class="movie__option"><strong>Release date: </strong>@movie.ReleaseDate</p>
                    <p class="movie__option"><strong>Director: </strong><a href="#">Jon Turteltaub</a></p>
                    <p class="movie__option"><strong>Actors: </strong><a href="#">@movie.Starring</a><a href="#">...</a></p>

                    <div class="movie__btns">

                        <a data-id="@movie.MovieId" class="editMovieBtn"><i class="fa fa-pencil"></i></a>
                        <a data-id="@movie.MovieId" class="deleteMovieBtn"><i class="fa fa-trash-o"></i></a>
                    </div>
                </div>

                <div class="clearfix"></div>



            </div>
            <!-- end movie preview item -->
        }
    
    </div>
</section>

<div class="clearfix"></div>

<div class="container">
    <div id="movieActionContainer">

    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        init_MovieList();
    });


    function focusAction(controlToFocus) {
        $("html, body").animate({
            scrollTop: $("#" + controlToFocus).offset().top - 100
        }, 1000);
    }

    $("#newMovieBtn").click(function () {
       $.ajax({
                url: '@Url.Action("AddMovie", "Movie")',
            })
                .done(function (response) {
                    $("#movieActionContainer").html(response);
                    focusAction("movieActionContainer");
                })
                .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                    alert("Fail")
                });
    });

    $(".editMovieBtn").click(function () {
       $.ajax({
           url: '@Url.Action("EditMovie", "Movie")',
           data: {
               Id: $(this).attr("data-id")
           }
            })
                .done(function (response) {
                    $("#movieActionContainer").html(response);
                    focusAction("movieActionContainer");
                })
                .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                    alert("Fail")
                });
    });

    $(".deleteMovieBtn").click(function () {
    swal({
        text: "Da li ste sigurni da želite da izbrišete ovaj film?",
        icon: "warning",
        buttons: true,
        dangerMode: true,
    })
        .then((willDelete) => {
            if (willDelete) {
                $.ajax({
                    type: 'POST',
                    url:'@Url.Action("DeleteMovie","Movie")',
                    data: {
                        Id: $(this).attr('data-id'),
                    }
                })
                    .done(function (response) {
                        swal("Film je uspešno izbrisan!", {
                            icon: "success",
                        }).then((value) => {
                          window.location = '@Url.Action("Index","Movie")';
                      });
                    })
                    .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                        alert("Fail")
                    });
            }
        });
});
</script>