BookingTicket/Controllers/ProjectionController.cs
using BookingTicket.Entities.Entities;
using BookingTicket.Service;
using BookingTicket.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookingTicket.Controllers
{
    public class ProjectionController : Controller
    {
        // GET: Projection
        public ActionResult Index()
        {
            ProjectionViewListingModel model = new ProjectionViewListingModel();
            model.Projections = ProjectionService.GetProjections();
            return View(model);
        }
        public ActionResult AddProjection()
        {
            ProjectionViewModel model = new ProjectionViewModel();
            model.Movies = MovieService.GetMovies();
            model.Halls = HallService.GetHalls();
            return PartialView(model);
        }

        [HttpPost]
        public JsonResult AddProjection(Projection projection)
        {
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;
            if(projection != null)
            {
                ProjectionService.AddProjection(projection);
                result.Data = new { Success = true };
            }
            else
            {
                result.Data = new { Success = false };
            }
            return result;
        }

        public JsonResult DeleteProjection(string Id)
        {
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;
            ProjectionService.DeleteProjection(Id);
            result.Data = new { Success = false };

            return result;

        }
    }
}

BookingTicket/Controllers/ReservationController.cs
using BookingTicket.Entities.Entities;
using BookingTicket.Service;
using BookingTicket.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookingTicket.Controllers
{
    public class ReservationController : Controller
    {
        // GET: Reservation
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AdminIndex()
        {
            var model = new ReservationAdminViewModel();
            model.Reservations = ReservationService.GetReservations();

            return View(model);
        }

        public ActionResult BookingStepOne()
        {
            ReservationViewModel model = new ReservationViewModel();
            model.Movies = MovieService.GetMovies();
            return PartialView(model);
        }

        public ActionResult BookingStepReserve()
        {
            return PartialView();
        }
  
        public ActionResult BookingReservationFinal(string chooseMovie, string chooseCity, string chooseDate,string chooseCinema,string chooseTime, string userEmail,string userPhoneNummber,string userTicket,string movieId)
        {
            Reservation reservation = new Reservation();
            reservation.MovieTitle = chooseMovie;
            reservation.City = chooseCity;
            reservation.Date = chooseDate;
            reservation.Time = chooseTime;
            reservation.Email = userEmail;
            reservation.PhoneNummber = userPhoneNummber;
            reservation.NummberOfTicket = userTicket;
            reservation.MovieId = movieId;
            reservation.Cinema = chooseCinema;

            ReservationService.AddReservation(reservation);

            var model = new ReservationFinalViewModel();
            model.Reservation = reservation;

            return PartialView(model);
        }
    }
}

BookingTicket/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookingTicket.Controllers
{
    public class SharedController : Controller
    {
        public JsonResult UploadImage()
        {
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;

            try
            {
                var file = Request.Files[0];

                var fileName = Guid.NewGuid() + Path.GetExtension(file.FileName);

                var path = Path.Combine(Server.MapPath("~/content/images/"), fileName);

                file.SaveAs(path);

                result.Data = new { Success = true, ImageUrl = string.Format("/content/images/{0}", fileName) };

            }
            catch (Exception ex)
            {
                result.Data = new { Success = false, Message = ex.Message };
            }
            return result;
        }
    }
}

BookingTicket/Views/Shared/_Layout.cshtml
<!doctype html>
<html>
<head>

    <!-- Font awesome - icon font -->
    <link href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
   
    <!-- Roboto -->
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,700' rel='stylesheet' type='text/css'>
    <!-- Open Sans -->
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:800italic' rel='stylesheet' type='text/css'>


    <!-- Stylesheets -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- External css files -->
    <!-- Select -->
    <link href="~/Content/css/external/jquery.selectbox.css" rel="stylesheet" />
    <!-- Swiper slider -->
    <link href="~/Content/css/external/idangerous.swiper.css" rel="stylesheet" />
    <!-- Magnific-popup -->
    <link href="~/Content/css/external/magnific-popup.css" rel="stylesheet" />
    <!-- REVOLUTION BANNER CSS SETTINGS -->
    <link href="~/Content/rs-plugin/css/settings.css" rel="stylesheet" type="text/css" media="screen" />

    <!-- Custom css files -->
    <!-- Mobile menu -->
    <link href="~/Content/css/gozha-nav.css" rel="stylesheet" />
    <!-- Touch -->
    <link href="~/Content/css/touch.css?v=1" rel="stylesheet" />
    <!-- Style -->
    <link href="~/Content/css/style.css?v=1" rel="stylesheet" />

    <!-- Modernizr -->
    <script src="~/Content/js/external/modernizr.custom.js"></script>

    <!-- jQuery 1.9.1 -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>

    <!-- jQuery UI -->
    <link href="https://code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css" rel="stylesheet">


    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/jquery.validate.min.js"></script>

</head>
<body>
    <div class="wrapper">
        <!-- Header section -->
        <header class="header-wrapper header-wrapper--home">
            <div class="container">
                <!-- Logo link-->
                <a href='@Url.Action("Index","Home")' class="logo">
                    <img alt='logo' src="~/Content/images/logo.png">
                </a>

                <!-- Main website navigation-->
                <nav id="navigation-box">
                    <!-- Toggle for mobile menu mode -->
                    <a href="#" id="navigation-toggle">
                        <span class="menu-icon">
                            <span class="icon-toggle" role="button" aria-label="Toggle Navigation">
                                <span class="lines"></span>
                            </span>
                        </span>
                    </a>

                  
                </nav>

                <!-- Additional header buttons / Auth and direct link to booking-->
                <div class="control-panel">
                    @if (!User.Identity.IsAuthenticated)
                    {
                        <div class="auth auth--home">
                            <div class="auth__show">
                                <span class="auth__image">
                                    <img alt="" src="~/Content/images/tickets.png">
                                </span>
                            </div>
                            <a class="btn btn--sign btn--singin">
                                Admin
                            </a>
                            <ul class="auth__function">
                                <li><a href="@Url.Action("Index","Movie")" class="auth__function-item">Filmovi</a></li>
                                <li><a href="@Url.Action("Index","Hall")" class="auth__function-item">Sale</a></li>
                                <li><a href="@Url.Action("Index","Projection")" class="auth__function-item">Projekcije</a></li>
                                <li><a href="@Url.Action("AdminIndex","Reservation")" class="auth__function-item">Rezervacije</a></li>
                            </ul>

                        </div>
                    }
                    else
                    {
                        <a href="@Url.Action("Login","Account")" class="btn btn--sign">Sign in</a>
                    }
                    <a href="@Url.Action("Index","Reservation")" class="btn btn-md btn--warning btn--book btn-control--home">Rezerviši kartu</a>
                </div>


            </div>
        </header>


        @RenderBody()

        <footer class="footer-wrapper">
            <section class="container">
                <div class="col-xs-4 col-md-2 footer-nav">
                    <ul class="nav-link">
                        <li><a href="#" class="nav-link__item">Cities</a></li>
                        <li><a href="movie-list-left.html" class="nav-link__item">Movies</a></li>
                        <li><a href="trailer.html" class="nav-link__item">Trailers</a></li>
                        <li><a href="rates-left.html" class="nav-link__item">Rates</a></li>
                    </ul>
                </div>
                <div class="col-xs-4 col-md-2 footer-nav">
                    <ul class="nav-link">
                        <li><a href="coming-soon.html" class="nav-link__item">Coming soon</a></li>
                        <li><a href="cinema-list.html" class="nav-link__item">Cinemas</a></li>
                        <li><a href="offers.html" class="nav-link__item">Best offers</a></li>
                        <li><a href="news-left.html" class="nav-link__item">News</a></li>
                    </ul>
                </div>
                <div class="col-xs-4 col-md-2 footer-nav">
                    <ul class="nav-link">
                        <li><a href="#" class="nav-link__item">Terms of use</a></li>
                        <li><a href="gallery-four.html" class="nav-link__item">Gallery</a></li>
                        <li><a href="contact.html" class="nav-link__item">Contacts</a></li>
                        <li><a href="page-elements.html" class="nav-link__item">Shortcodes</a></li>
                    </ul>
                </div>
                <div class="col-xs-12 col-md-6">
                    <div class="footer-info">
                        <p class="heading-special--small">A.Movie<br><span class="title-edition">in the social media</span></p>

                        <div class="social">
                            <a href='#' class="social__variant fa fa-facebook"></a>
                            <a href='#' class="social__variant fa fa-twitter"></a>
                            <a href='#' class="social__variant fa fa-vk"></a>
                            <a href='#' class="social__variant fa fa-instagram"></a>
                            <a href='#' class="social__variant fa fa-tumblr"></a>
                            <a href='#' class="social__variant fa fa-pinterest"></a>
                        </div>

                        <div class="clearfix"></div>
                        <p class="copy">&copy; A.Movie, 2021. Sva prava zadržana.</p>
                    </div>
                </div>
            </section>
        </footer>
    </div>

    <!--Scripts-->
    <!-- Core js files -->
    <script>window.jQuery || document.write('<script src="~/Content/js/external/jquery-1.10.1.min.js"><\/script>')</script>
    <!-- Migrate -->
    <script src="~/Content/js/external/jquery-migrate-1.2.1.min.js"></script>
    <!-- jQuery UI -->
    <script src="https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
    <!-- Bootstrap 3 -->
    <script src="https://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <!-- Modernizr -->
    <script src="~/Content/js/external/modernizr.custom.js"></script>

    <!-- Slider -->
    <!-- jQuery REVOLUTION Slider -->
    <script type="text/javascript" src="~/Content/rs-plugin/js/jquery.themepunch.plugins.min.js"></script>
    <script type="text/javascript" src="~/Content/rs-plugin/js/jquery.themepunch.revolution.js"></script>
    <!-- Swiper slider -->
    <script src="~/Content/js/external/idangerous.swiper.min.js"></script>

    <!-- Files (js) for improve interface -->
    <!-- Mobile menu -->
    <script src="~/Content/js/jquery.mobile.menu.js"></script>
    <!-- Select -->
    <script src="~/Content/js/external/jquery.selectbox-0.2.min.js"></script>
    <!-- Stars rate -->
    <script src="~/Content/js/external/jquery.raty.js"></script>
    <!-- Form element -->
    <script src="~/Content/js/external/form-element.js"></script>
    <!-- Form validation -->
    <script src="~/Content/js/form.js"></script>

    <!-- Knob js -->
    <script src="~/Content/js/external/jquery.knob.js"></script>
    <!-- Count comimg soon -->
    <script src="~/Content/js/external/count.down.js"></script>
    <!-- Magnific-popup -->
    <script src="~/Content/js/external/jquery.magnific-popup.min.js"></script>
    <!-- Share buttons -->
    <script type="text/javascript">var addthis_config = { "data_track_addressbar": true };</script>
    <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-525fd5e9061e7ef0"></script>
    <!-- Inview -->
    <script src="~/Content/js/external/jquery.inview.js"></script>

    <!-- Maps -->
    <!-- *** Google map *** -->
    <script src="https://maps.google.com/maps/api/js?sensor=true"></script>
    <!-- *** Google map infobox *** -->
    <script src="~/Content/js/external/infobox.js"></script>

    <!-- Custom -->
    <script src="~/Content/js/custom.js"></script>
    <script>
        $('.btn--singin').click(function (e) {

            e.preventDefault();
            $('.auth__function').toggleClass('open-function')
        });
    </script>
</body>
</html>